spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 2097152
      max-request-size: 10485760  
mybatis:
  config-location: classpath:Configuration.xml    
